# Generated by Django 3.2.9 on 2021-12-06 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.ManyToManyField(to='schedule.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('sex', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=6)),
                ('birth_date', models.DateField()),
                ('staff_type', models.CharField(choices=[('dr', 'Bác Sĩ'), ('nu', 'Điều Dưỡng / Hộ Sinh'), ('te', 'Kỹ Thuật Viên'), ('st', 'Nhân viên khối hành chính'), ('cl', 'Hộ Lý')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.role')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.staff')),
            ],
        ),
    ]
