# Generated by Django 3.2.9 on 2021-12-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='staff',
            field=models.ManyToManyField(to='schedule.Staff'),
        ),
    ]
